### ISSUE TITLE
FR: add a site

### ISSUE THREAD

**Issue by olivroy** [thomasp85/marquee#14]
I think this project looks interesting!

But I'd love to see it in a pkgdown format!

Running 

```r
usethis::use_pkgdown_github_pages()
```

should do the trick

**Comment by thomasp85** [comment]
Thanks -- a pkgdown site will come, but only once the package is ready. A site kind of advertises broad use which this 2 week old package is not ready for yet

**Comment by olivroy** [comment]
Alright! I will build it locally, I'd just love to see what the rendered examples look like!
