### ISSUE TITLE
glue-like string interpolation?

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/marquee#6]

**Comment by olivroy** [comment]
Supporting cli inline markup would be awesome!

https://cli.r-lib.org/reference/inline-markup.html

Is there already a way to do this with ggplot2.

```r
str <- cli::format_inline('{cli::col_red("Important things")} is {.val 1}')
cat(str, sep = "\n")
```
![image](https://github.com/thomasp85/marquee/assets/52606734/449d9194-bf35-4a9c-9929-c8cc1eb01ac6)

It would be great if this kind of syntax could be used in some way to add as ggplot2 title

```r
library(ggplot2)
ggplot(mtcars) +
  labs(title = str)
```

It would be great if there was a way for ggplot2 to recognize a syntax that allows coloring / styling.

The already existing cli syntax for markup could be used / recognized?

cli has `ansi_html()`, which may help?

```r
cli::ansi_html(str)
```

**Comment by thomasp85** [comment]
Understanding cli styling is out of scope, but you can color text using custom spans such as `{.red this will be red}` (which is very akin to cli syntax). In the same way you can make custom styles
