### ISSUE TITLE
Honor parent vp clipping

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/marquee#8]
I cannot figure out why this is but marquee grobs are not clipped by the parent viewport

```r
pushViewport(viewport(width = 0.5, height = 0.5, clip = "on"))
grid.draw(marquee_grob(markdown_test, classic_style(), width = NA))
```

![image](https://github.com/thomasp85/marquee/assets/1775316/f0520011-e539-438c-8053-edfd90663f5a)

**Comment by teunbrand** [comment]
It is become some grobs/grobTrees have fixed viewport clipping settings, like `clip = "off"` or `clip = <grob>` that overrides inheritance from the parent viewport. I'm not sure how this is supposed to be done though.

**Comment by thomasp85** [comment]
Hmm, I thought viewport clipping was cumulative, not an on/off switch
